### ISSUE TITLE
Panic (cannot create GL context)

### ISSUE THREAD

**Issue by cjwelborn** [anmej/piston-falling-sand-prototype#1]
Compiled completely with `rustc 1.2.0-nightly (a9515698f 2015-06-20)`, and got this error when running (both debug and `--release`). This happens immediately, I guess when trying to create the window:

```
thread '<main>' panicked at 
'called `Result::unwrap()` on an `Err` value: "Could not create GL context"', 
../src/libcore/result.rs:731
```

Any idea what might cause this? A missing library? I'm running `Kubuntu 14.04` and I did have to install `libsdl2-dev` before I could compile it.

**Comment by anmej** [comment]
I'm afraid I have no idea what causes this, I haven't tried to compile the last version on linux, but a few days ago it did compile and run on Ubuntu.

**Comment by cjwelborn** [comment]
After checking around I think this has to do with my drivers. Other OpenGL stuff seems to work fine, and  `glxgears` and all that work like they are supposed to. Either way, I don't think it has anything to do with your prototype so I'll close this.
